[package]
name = "heroku-go-utils"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
libherokubuildpack = { workspace = true }
regex = "1"
semver = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
